server:
  servlet:
    context-path: "/"

spring:
  profiles:
    active: ${PROFILE_ACTIVE}
  jpa:
    show-sql: false


ai:
  openai:
    url: "https://api.openai.com/v1/chat/completions"
    key: ${OPENAI_KEY}

  hugging:
    url: ${HUGGING_URL}
    key: ${HUGGING_KEY}


similarity:
  api:
    url: ${SIMILARITY_API_KEY}


logging:
  level:
    org:
      springframework:
        messaging: DEBUG
        web:
          socket: DEBUG
    com:
      knowzone: DEBUG